### ISSUE TITLE
what does local proxy listen port mean?

### ISSUE THREAD

**Issue by yilovezy** [ShadowsocksR-Live/ssrWin#2]

**Comment by ssrlive** [comment]
there exist two local proxy server. SSR client act as an S5 server. Privoxy app act as http proxy server. and privoxy connect to S5 server.

```
your browser <--> privoxy <--> S5 server <--> SSR remote server
                    |         (SSR client)
                    |
            (local proxy listen port)
```

**Comment by ssrlive** [comment]
Normal users don't need to care about these settings, just use the default options.
