### ISSUE TITLE
ssrot connection fails with websocket error "Bad Gateway"

### ISSUE THREAD

**Issue by shangjiaxuan** [ShadowsocksR-Live/ssrWin#3]
A problem with TAP-Adapter? Client and server config works for the old ssr-native text based manual proxy chain.

```
ssrWin 2021/03/16 10:24  info  ==== tunnel created     count   1 ====
ssrWin 2021/03/16 10:24  info  tunnel_stage_handshake -- Client App S5 handshake coming.
ssrWin 2021/03/16 10:24  info  tunnel_stage_handshake_replied -- Start waiting for request data.
ssrWin 2021/03/16 10:24  info  tunnel_stage_s5_request_from_client_app -- SOCKS5 Request data from client app.
ssrWin 2021/03/16 10:24  info  tunnel_stage_s5_response_done
ssrWin 2021/03/16 10:24  info  tunnel_stage_client_first_pkg
ssrWin 2021/03/16 10:24  info  ++++ connecting  "www.google.com:443" ... ++++
ssrWin 2021/03/16 10:24 error  [TLS] websocket error at "www.google.com:443" with status: Bad Gateway
```

**Comment by ssrlive** [comment]
估计服务端出了问题。

**Comment by shangjiaxuan** [comment]
> 
> 
> 估计服务端出了问题。
> 
> 如果你不是重度翻墙用户，建议 [使用 heroku 的免费主机容器](https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki/%E5%85%A8%E8%87%AA%E5%8A%A8%E5%AE%89%E8%A3%85-SSRoT-%E6%9C%8D%E5%8A%A1%E5%99%A8#%E5%9C%A8-heroku-%E4%B8%8A%E9%83%A8%E7%BD%B2-ssrot-%E6%9C%8D%E5%8A%A1%E7%AB%AF) 用两个账号注册，轮换着每个用半月，基本上日常工作学习的翻墙需求都解决了。

我用ssr-native仓库的ssr-client手动配置浏览器使用本地转发的socks5可以正常使用，不是服务器端问题。服务器端我是自己部署的。

**Comment by ssrlive** [comment]
目前客户端 TAP 全局翻墙方案尚未调通。使用 ssrWin 时请停掉其它翻墙软件。
