### ISSUE TITLE
wsl局域网共享问题

### ISSUE THREAD

**Issue by I2Cold** [ShadowsocksR-Live/ssrWin#7]
请问可以支持局域网共享吗，跑wsl2需要

**Comment by ssrlive** [comment]
可以共享 socks5 代理，但不能共享 privoxy的 http 代理。

**Comment by I2Cold** [comment]
> 可以共享 socks5 代理，但不能共享 privoxy的 http 代理。 ![image](https://github.com/ShadowsocksR-Live/ssrWin/assets/30760636/5a95cf11-8984-4e7c-a3b6-8526b970ec7d)
按图设置重新运行，但仍然无法使用。而用[shadowsocksr-csharp](https://github.com/shadowsocksrr/shadowsocksr-csharp)则可以，但那样就没法用overtls
1080是ssr-csharp，40404是ssrWin
![image](https://github.com/ShadowsocksR-Live/ssrWin/assets/63573296/4c645ebc-0a7d-4e18-a537-0fd91ebd3dd2)

**Comment by ssrlive** [comment]
你同網段的其它機器可以訪問 這個機器的 40404 嗎？如果可以，那就不是 ssrwin 的問題了。

**Comment by I2Cold** [comment]
可以

**Comment by ssrlive** [comment]
我注意到了， `export https_proxy='....'` 會改變 curl 的行爲。

**Comment by ssrlive** [comment]
可能是 GFW 的DNS 污染，在 wsl 裏 查詢 google 的地址會被 gfw 搞掉。

**Comment by ssrlive** [comment]
但如果 走 `curl --proxy socks5h://.... https://google.com` 的話，curl 不會查詢 dns ， 直接把 域名打包給 socks5 代理了。

**Comment by ssrlive** [comment]
你可以使用我的 dns2socks 玩具，將 dns 查詢截胡到 socks5 代理上。

https://github.com/ssrlive/socks5-impl/releases

**Comment by I2Cold** [comment]
> 但如果 走 `curl --proxy socks5h://.... https://google.com` 的話，curl 不會查詢 dns ， 直接把 域名打包給 socks5 代理了。

非也，在wsl裏即使是用國內的網站，同樣連接不上。不知為何在wsl中總是會連接失敗
![image](https://github.com/ShadowsocksR-Live/ssrWin/assets/63573296/13acc98f-ea14-4ad4-aa72-518c666e8105)

**Comment by ssrlive** [comment]
是 `socks5h` 不是 `socks5`

**Comment by ssrlive** [comment]
curl 自己給自己加了戲。

**Comment by I2Cold** [comment]
結果是一樣的，用了socks5h也如此
![image](https://github.com/ShadowsocksR-Live/ssrWin/assets/63573296/c0eeef84-f4e7-4e41-a562-1356a38d17e3)

**Comment by ssrlive** [comment]
那你 wsl 有什麼問題？ 把監聽端口改小點 10000 以內有問題嗎。

**Comment by I2Cold** [comment]
跟端口數值沒關係，我試過把ssrwin和shadowsocksr-csharp的監聽端口交換，情況仍然如此

**Comment by ssrlive** [comment]
就 wsl 有問題， 其它機器沒問題？

**Comment by ssrlive** [comment]
如果是這樣，那就可以確定 就是 wsl 的問題了。

**Comment by ssrlive** [comment]
我不用 wsl 我只用 vm 虛擬機。搞不清情況。

**Comment by I2Cold** [comment]
> 就 wsl 有問題， 其它機器沒問題？

是的

> 可以，搞不懂為什麼會這樣。那只能在wsl2用其他來連了

其他機器是可以用的

**Comment by ssrlive** [comment]
你試試命令行程序？看看它的日誌輸出是啥？

https://github.com/ShadowsocksR-Live/overtls/releases
