### ISSUE TITLE
win10 22H2 64位操作系统不明原因的卡死

### ISSUE THREAD

**Issue by chenxudong2020** [ShadowsocksR-Live/ssrWin#8]
添加之後 點擊Run 頁面無響應 一直卡死只能任務管理器強製結束
![image](https://github.com/ShadowsocksR-Live/ssrWin/assets/61214170/c20061c6-bbff-4fde-b2b4-b5864d4430ef)
軟件最新版本0.8.8 x64
安卓手機酸酸乳測試 正常說明overtls服務器是正常的
具體配置如下：path已經做了隱藏
![1707378024(1)](https://github.com/ShadowsocksR-Live/ssrWin/assets/61214170/39948714-8fff-4b0e-9c59-59311d9f70fd)

把加密方式設置none 就卡死 設置成別的就能啟動 。。。。。

**Comment by ssrlive** [comment]
不行. 流氓警察盯着呢.

**Comment by ssrlive** [comment]
奇怪. 我 win 11 测试没问题. 🤔️.

**Comment by ssrlive** [comment]
好! 我测试一把 win 10. 谢谢报告问题.

**Comment by ssrlive** [comment]
你的选项设置是啥,也贴个截图.

**Comment by chenxudong2020** [comment]
图我不是已经截图了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月8日(周四) 晚上6:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ShadowsocksR-Live/ssrWin] win10 22H2 64位操作系统不明原因的卡死 (Issue #8)




 
你的选项设置是啥,也贴个截图.

**Comment by ssrlive** [comment]
这个.

![Screenshot 2024-02-08 at 18 27 34](https://github.com/ShadowsocksR-Live/ssrWin/assets/30760636/3cbfa64e-0342-4413-b6f9-7329d8f4db6a)

**Comment by chenxudong2020** [comment]
默认



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月8日(周四) 晚上6:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ShadowsocksR-Live/ssrWin] win10 22H2 64位操作系统不明原因的卡死 (Issue #8)




 
你的选项设置是啥,也贴个截图.

**Comment by ssrlive** [comment]
剛剛在 win 7 上測試通過，沒問題。我硬盤太小，無法再裝 win 10 虛擬機了，很遺憾測不了。

**Comment by chenxudong2020** [comment]
额😓 先挂着吧 等反馈&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月8日(周四) 晚上8:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ShadowsocksR-Live/ssrWin] win10 22H2 64位操作系统不明原因的卡死 (Issue #8)




 
剛剛在 win 7 上測試通過，沒問題。我硬盤太小，無法再裝 win 10 虛擬機了，很遺憾測不了。

**Comment by ssrlive** [comment]
overtls 的命令行客戶端有卡死嗎？

**Comment by chenxudong2020** [comment]
没有啊&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月8日(周四) 晚上8:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ShadowsocksR-Live/ssrWin] win10 22H2 64位操作系统不明原因的卡死 (Issue #8)




 
overtls 的命令行客戶端有卡死嗎？

**Comment by chenxudong2020** [comment]
已经找到原因了    上面的 Server Address 写成了**域名**导致 软件启动时候报错卡死了...................................
无语死了。。。。。。。。。。。。。。。。。。。。。
能不能去掉此项设置 因为域名有了 软件自动解析ip 这个是可以的

**Comment by ssrlive** [comment]
嗯. 考虑一下怎么改.可能要修改多个地方.

**Comment by ssrlive** [comment]
fixed at https://github.com/ShadowsocksR-Live/overtls/commit/3dbff37410e95375d4452f7b9bf79755e4e4a0ba
